// <auto-generated />
using System;
using Forum.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Forum.API.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260121180918_DataSeed")]
    partial class DataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Forum.API.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dae65b74-fd79-47ab-aa78-df29cae7351b"),
                            CommentDate = new DateTime(2026, 1, 22, 22, 9, 17, 469, DateTimeKind.Local).AddTicks(5052),
                            Content = "Hello Comment!",
                            TopicId = new Guid("7d5f3b62-71dc-4683-8665-5342b8a17975")
                        },
                        new
                        {
                            Id = new Guid("46c36068-13ab-47a3-a1e5-e74e07d888cb"),
                            CommentDate = new DateTime(2026, 1, 23, 22, 9, 17, 469, DateTimeKind.Local).AddTicks(5631),
                            Content = "Hello Comment!",
                            TopicId = new Guid("e80d9e8d-4fa3-4a55-8bc7-b51fd8542f18")
                        });
                });

            modelBuilder.Entity("Forum.API.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CommentsAreAllowed")
                        .HasColumnType("bit");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("Date");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastCommentDate")
                        .HasColumnType("Date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7d5f3b62-71dc-4683-8665-5342b8a17975"),
                            CommentsAreAllowed = true,
                            Content = "Hello World!",
                            CreateDate = new DateTime(2026, 1, 21, 22, 9, 17, 468, DateTimeKind.Local).AddTicks(8934),
                            LastCommentDate = new DateTime(2026, 1, 21, 22, 9, 17, 468, DateTimeKind.Local).AddTicks(9371),
                            Title = "First Topic"
                        },
                        new
                        {
                            Id = new Guid("e80d9e8d-4fa3-4a55-8bc7-b51fd8542f18"),
                            CommentsAreAllowed = true,
                            Content = "Hello World!",
                            CreateDate = new DateTime(2026, 1, 21, 22, 9, 17, 468, DateTimeKind.Local).AddTicks(9661),
                            LastCommentDate = new DateTime(2026, 1, 21, 22, 9, 17, 468, DateTimeKind.Local).AddTicks(9662),
                            Title = "Second Topic"
                        },
                        new
                        {
                            Id = new Guid("1cc11272-2f02-4bca-a0f8-abd32f970a32"),
                            CommentsAreAllowed = true,
                            Content = "Hello World!",
                            CreateDate = new DateTime(2026, 1, 21, 22, 9, 17, 468, DateTimeKind.Local).AddTicks(9664),
                            LastCommentDate = new DateTime(2026, 1, 21, 22, 9, 17, 468, DateTimeKind.Local).AddTicks(9664),
                            Title = "Second Topic"
                        });
                });

            modelBuilder.Entity("Forum.API.Entities.Comment", b =>
                {
                    b.HasOne("Forum.API.Entities.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });
#pragma warning restore 612, 618
        }
    }
}
